name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install bats
      - run: npm install -g bats
      - name: check version
      - run: bats -v
      - name: build
      - run: npm run build
      - name: run tests
      - run: npm run test
